name: Release
on: 
  push:
    branches:
      - master
jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-18.04
    outputs:
      new_tag: ${{ steps.github_tag_action.outputs.new_tag }}
      changelog: ${{ steps.github_tag_action.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: github_tag_action
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.TOKEN_MOC_GH }}
          release_branches: .*
          default_bump: fix
          
          
  create_release:
    name: Create Release
    runs-on: ubuntu-18.04
    needs: bump_version
    if: ${{ needs.bump_version.outputs.new_tag != null }}
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: HW Rev
        run: |
           free -h
           lscpu
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Build image
        run: docker build -t builder_webapp -f Dockerfile .
      
      - name: Build With image
        run: docker run --rm --name webapp-IPFS-compiler --env TOOL_NODE_FLAGS="--max-old-space-size=4096" -v "$(pwd)"/build/:/usr/src/app/build -v "$(pwd)"/src/:/usr/src/app/src -v "$(pwd)"/public/:/usr/src/app/public builder_webapp


      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: MoC ${{ needs.bump_version.outputs.new_tag }}
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}
          
      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}



      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NF }}
        with:
          tag_name: ${{ needs.bump_version.outputs.new_tag }}
          release_name: Release ${{ needs.bump_version.outputs.new_tag }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.upload.outputs.hash }}`
            - CIDv1: `${{ steps.convert_cidv0.outputs.cidv1 }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [ipfs.moneyonchain.com](https://ipfs.moneyonchain.com).
            You can also access the Moc Interface directly from an IPFS gateway.
            **BEWARE**: The MoC interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as which tokens you have imported.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.uniswap.org](https://ipfs.moneyonchain.com.
            Your Uniswap settings are never remembered across different URLs.
            IPFS gateways:
            - https://gateway.pinata.cloud/ipfs/${{ steps.upload.outputs.hash }}
            - https://cloudflare-ipfs.com/ipfs/${{ steps.upload.outputs.hash }}
            - https://ipfs.io/ipfs/${{ steps.upload.outputs.hash }}
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.upload.outputs.hash }}/)
            ${{ needs.bump_version.outputs.changelog }}
